<?php
ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);

    $returndata = array();
    $returnArray = null;
    $extra = "";
	$fieldName = "";
	$tableName = "";
	$previousValue = "";
	$conditions = null;
	
    require $_SERVER['DOCUMENT_ROOT'] . "/lib/dbconfig.php";

    $pdo = new PDO("mysql:host=$host;dbname=$dbname", $username, $password);
	
	if($_POST['fieldTable']){
		$fieldName = $_POST['fieldTable'][0];
		$tableName = $_POST['fieldTable'][1];
		$previousValue = $_POST['fieldTable'][2];
	}
	if($_POST['conditions']){
		$conditions = $_POST['conditions'];
	}
    $query = "SELECT DISTINCT " . $fieldName . " FROM " . $tableName; //able to add on other conditions if needed
    
	if( isset($conditions) ){
		$query = $query . " WHERE " . $conditions[0] . "=" . $conditions[1];
		$cond_length = count($conditions);
		for($i=2;$i<$cond_length;$i+=2){
			$query = $query . " AND " . $conditions[$i] . "=" . $conditions[$i+1];
		}
	}
	$queryFinal = $query . " ORDER BY " . $fieldName . " ASC;";
	echo "\n--> " . $queryFinal . "\n";
    $result = $pdo->query($queryFinal);
    $result->setFetchMode(PDO::FETCH_ASSOC);

    $i = 0;
    $j = 0;
    $alreadyFound = array();

    while ($row = $result->fetch(PDO::FETCH_ASSOC)) {
        if (! empty($row)) {

            $returnArray[$i] = $row;
            $i ++;
            $skipRest = "false";
        } else {
            echo "<option value=\"none\">No records avail</option>\n";
            $skipRest = "true";
        }
    }

    if ($skipRest != "true") {

        if (! empty($previousValue)) {
            echo "<option name=\"" . $fieldName . "\"value=\"\" >- select -</option>\n";
        } else {
            echo "<!-- *** dropdown box \"<option>\" values are auto-generated by code -->\n";
            echo "<option name=\"" . $fieldName . "\"value=\"\" selected>- select -</option>\n";
        }
        foreach ($returnArray as $row) {
            foreach ($row as $key => $val) {
                if ($val == $previousValue) {
                    $extra = "selected";
                }
                if (! in_array($val, $alreadyFound) && ($val != "")) { // don't add duplicate or blank values to the list
                    if ($key == $fieldName) {
                        echo "<option name=\"" . $fieldName . "\" value=\"" . htmlspecialchars($val) . "\" " . $extra . ">" . htmlspecialchars($val) . "</option>\n";
                    } else {
                        echo "<option value=\"none\">No records avail</option>\n";
                    }
                }
                $alreadyFound[$j] = $val;
                $j ++;
                $extra = "";
            }
        }
        // echo "<option value=\"0000\" selected>- select -</option>\n";
    }

    $pdo = null;
?>